---
title: "DataAnalysis"
output: pdf_document
date: "2026-05-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
##setwd("/cloud/project")
```

```{r}
combineddata<-read.csv("CData.csv")

##Add date column by combining year and month
combineddata <- combineddata %>%
  mutate(date_col = make_date(Year, Month, 1))

## Initial Plots
# Snowfall by Year
combineddata %>%
  filter(Month == 10) %>%
  ggplot(aes(x = date_col, y = TotalSnow)) + geom_point() + geom_line() + labs(title = "Total Snowfall by Year", x = "Year", y = "Total Snowfall (in)") + theme(plot.title = element_text(hjust = 0.5))

# Rainfall by Month
ggplot(data = combineddata, aes(x = date_col, y = TotalRain)) + geom_point() + geom_line() + labs(title = "Rainfall by Month", x = "Date", y = "Total Rainfall (in)") + theme(plot.title = element_text(hjust = 0.5))

# Birch Brook Temperature by Month
ggplot(data = combineddata, aes(x = date_col, y = BBAvgTemp)) + geom_point() + geom_line() + labs(title = "Birch Brook Temperature by Month", x = "Date", y = "Temperature (°C)") + theme(plot.title = element_text(hjust = 0.5))

# Birch Brook Discharge by Month
ggplot(data = combineddata, aes(x = date_col, y = BBAvgDischarge)) + geom_point() + geom_line() + labs(title = "Birch Brook Discharge by Month", x = "Date", y = "Discharge (ft^3/s)") + theme(plot.title = element_text(hjust = 0.5))

```

```{r}
## multiple linear regression for Discharge
moddis<-lm(formula=BBAvgDischarge~TotalSnow + TotalRain + FrontHeavy + BBAvgTemp, data=combineddata)
summary(moddis)

##multiple linear regression for Temp
modtemp<-lm(formula=BBAvgTemp~TotalSnow + TotalRain + FrontHeavy + BBAvgDischarge, data=combineddata)
summary(modtemp)

ggplot(data=combineddata, aes(x=TotalSnow, y=BBAvgDischarge + BBAvgTemp))+geom_point()+geom_smooth(method="lm")

## Anova Test for Discharge
anova <- aov(BBAvgDischarge ~ TotalSnow + BBAvgTemp + TotalRain + FrontHeavy, data = combineddata)
summary(anova)
## Anova Test for Temp
anova <- aov(BBAvgTemp ~ TotalSnow + BBAvgDischarge + TotalRain + FrontHeavy, data = combineddata)
summary(anova)


monthData <- combineddata %>% group_split(Month)
mayData <- monthData[[1]]
juneData <- monthData[[2]]
julyData <- monthData[[3]]
augustData <- monthData[[4]]
septemberData <- monthData[[5]]
octoberData <- monthData[[6]]

mayTemp <- lm(formula=BBAvgTemp~TotalSnow + MaxSnowDay + FrontHeavy+ TotalRain, data=mayData)
juneTemp <- lm(formula=BBAvgTemp~TotalSnow + MaxSnowDay + FrontHeavy+ TotalRain, data=juneData)
julyTemp <- lm(formula=BBAvgTemp~TotalSnow + MaxSnowDay + FrontHeavy+ TotalRain, data=julyData)
augustTemp <- lm(formula=BBAvgTemp~TotalSnow + MaxSnowDay + FrontHeavy+ TotalRain, data=augustData)
septemberTemp <- lm(formula=BBAvgTemp~TotalSnow + MaxSnowDay + FrontHeavy+ TotalRain, data=septemberData)
octoberTemp <- lm(formula=BBAvgTemp~TotalSnow + MaxSnowDay + FrontHeavy+ TotalRain, data=octoberData)

mayDis <- lm(formula=BBAvgDischarge~TotalSnow + MaxSnowDay + FrontHeavy + TotalRain, data=mayData)
juneDis <- lm(formula=BBAvgDischarge~TotalSnow + MaxSnowDay + FrontHeavy+ TotalRain, data=juneData)
julyDis <- lm(formula=BBAvgDischarge~TotalSnow + MaxSnowDay + FrontHeavy+ TotalRain, data=julyData)
augustDis <- lm(formula=BBAvgDischarge~TotalSnow + MaxSnowDay + FrontHeavy+ TotalRain, data=augustData)
septemberDis <- lm(formula=BBAvgDischarge~TotalSnow + MaxSnowDay + FrontHeavy+ TotalRain, data=septemberData)
octoberDis <- lm(formula=BBAvgDischarge~TotalSnow + MaxSnowDay + FrontHeavy+ TotalRain, data=octoberData)

summary(mayDis)
summary(juneDis)
summary(julyDis)
summary(augustDis)
summary(septemberDis)
summary(octoberDis)

summary(mayTemp)
summary(juneTemp)
summary(julyTemp)
summary(augustTemp)
summary(septemberTemp)
summary(octoberTemp)
```


